train:
  dataset_config:
    data_type: train
    img_size: 32

val:
  dataset_config:
    data_type: train
    img_size: 32

mode:
  train:
    batch_size: 128
    shuffle: True
  val:
    batch_size: 1024
    shuffle: False