train:
  data_type: train
  augmentation:
    - crop
    - horizontal_flip

val:
  data_type: val
  augmentation:
    - crop
    - horizontal_flip

mode:
  train:
    batch_size: 64
    shuffle: True
  val:
    batch_size: 128
    shuffle: False