train:
  dataset_config:
    data_type: train
    img_size: 32
    auto_augment_str: rand-m1-mstd0.5-inc1

val:
  dataset_config:
    data_type: train
    img_size: 32

workers: 4

mode:
  train:
    batch_size: 128
    shuffle: True
  val:
    batch_size: 1024
    shuffle: False